// pages/dashboard/profile.vue
<template>
  <div>
    <h1 class="text-2xl font-bold mb-6">My Profile</h1>
    
    <DataLoader :loading="loading" :error="error" type="card" :skeleton-props="{ rows: 4 }">
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <!-- Profile Card -->
        <div class="bg-white rounded-lg shadow-md border border-gray-200 overflow-hidden">
          <div class="p-6 flex flex-col items-center">
            <div class="relative mb-4">
              <div class="h-24 w-24 rounded-full bg-gray-200 flex items-center justify-center text-gray-700 text-2xl font-semibold">
                {{ userInitials }}
              </div>
              <button class="absolute bottom-0 right-0 bg-blue-600 text-white rounded-full p-1 shadow-sm">
                <CameraIcon class="h-5 w-5" />
              </button>
            </div>
            
            <h2 class="text-xl font-bold">{{ userData.fullName }}</h2>
            <p class="text-gray-500 mb-2 flex items-center">
              <EnvelopeIcon class="h-4 w-4 mr-1" />
              {{ userData.email }}
            </p>
            <span class="px-3 py-1 bg-blue-100 text-blue-800 text-xs font-semibold rounded-full flex items-center">
              <ShieldCheckIcon class="h-3 w-3 mr-1" />
              {{ userData.role }}
            </span>
            
            <div class="w-full mt-6 space-y-4">
              <div>
                <p class="text-sm text-gray-500 flex items-center">
                  <BuildingOfficeIcon class="h-4 w-4 mr-1" />
                  Department
                </p>
                <p class="font-medium">{{ userData.department }}</p>
              </div>
              
              <div>
                <p class="text-sm text-gray-500 flex items-center">
                  <MapPinIcon class="h-4 w-4 mr-1" />
                  Location
                </p>
                <p class="font-medium">{{ userData.location }}</p>
              </div>
              
              <div>
                <p class="text-sm text-gray-500 flex items-center">
                  <CalendarIcon class="h-4 w-4 mr-1" />
                  Member Since
                </p>
                <p class="font-medium">{{ userData.memberSince }}</p>
              </div>
              
              <div>
                <p class="text-sm text-gray-500 flex items-center">
                  <ClockIcon class="h-4 w-4 mr-1" />
                  Last Login
                </p>
                <p class="font-medium">{{ userData.lastLogin }}</p>
              </div>
            </div>
          </div>
        </div>
        
        <!-- Profile Details -->
        <div class="bg-white rounded-lg shadow-md border border-gray-200 overflow-hidden lg:col-span-2">
          <div class="flex border-b border-gray-200">
            <button 
              v-for="tab in tabs" 
              :key="tab.id" 
              @click="activeTab = tab.id" 
              class="px-6 py-3 text-sm font-medium focus:outline-none flex items-center"
              :class="activeTab === tab.id ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500 hover:text-gray-700'"
            >
              <component :is="tab.icon" class="h-4 w-4 mr-2" />
              {{ tab.name }}
            </button>
          </div>
          
          <!-- Information Tab -->
          <div v-if="activeTab === 'information'" class="p-6">
            <h2 class="text-lg font-semibold mb-1 flex items-center">
              <UserIcon class="h-5 w-5 mr-2 text-blue-600" />
              Profile Details
            </h2>
            <p class="text-sm text-gray-500 mb-6">Manage your personal information and account security</p>
            
            <DataLoader :loading="false" :error="null" type="form" :skeleton-props="{ fields: 6 }">
              <div class="space-y-6">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1 flex items-center">
                      <UserIcon class="h-4 w-4 mr-1" />
                      Username
                    </label>
                    <input type="text" v-model="userData.username" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                  </div>
                  
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1 flex items-center">
                      <IdentificationIcon class="h-4 w-4 mr-1" />
                      Full Name
                    </label>
                    <input type="text" v-model="userData.fullName" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                  </div>
                </div>
                
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1 flex items-center">
                      <EnvelopeIcon class="h-4 w-4 mr-1" />
                      Email
                    </label>
                    <input type="email" v-model="userData.email" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                  </div>
                  
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1 flex items-center">
                      <PhoneIcon class="h-4 w-4 mr-1" />
                      Phone
                    </label>
                    <input type="tel" v-model="userData.phone" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                  </div>
                </div>
                
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1 flex items-center">
                      <BuildingOfficeIcon class="h-4 w-4 mr-1" />
                      Department
                    </label>
                    <input type="text" v-model="userData.department" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                  </div>
                  
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1 flex items-center">
                      <MapPinIcon class="h-4 w-4 mr-1" />
                      Location
                    </label>
                    <input type="text" v-model="userData.location" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                  </div>
                </div>
                
                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-1 flex items-center">
                    <DocumentTextIcon class="h-4 w-4 mr-1" />
                    Bio
                  </label>
                  <textarea v-model="userData.bio" rows="4" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"></textarea>
                </div>
                
                <div class="flex justify-end">
                  <button 
                    @click="saveProfile"
                    :disabled="saving"
                    class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md shadow-sm flex items-center disabled:opacity-50"
                  >
                    <CheckCircleIcon v-if="!saving" class="h-4 w-4 mr-2" />
                    <div v-else class="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                    {{ saving ? 'Saving...' : 'Save Changes' }}
                  </button>
                </div>
              </div>
            </DataLoader>
          </div>
          
          <!-- Security Tab -->
          <div v-if="activeTab === 'security'" class="p-6">
            <h2 class="text-lg font-semibold mb-1 flex items-center">
              <ShieldCheckIcon class="h-5 w-5 mr-2 text-blue-600" />
              Security
            </h2>
            <p class="text-sm text-gray-500 mb-6">Manage your password and account security</p>
            
            <div class="space-y-6">
              <div>
                <h3 class="text-sm font-medium text-gray-700 mb-3 flex items-center">
                  <KeyIcon class="h-4 w-4 mr-2" />
                  Change Password
                </h3>
                <div class="space-y-4">
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Current Password</label>
                    <input type="password" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                  </div>
                  
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">New Password</label>
                    <input type="password" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                  </div>
                  
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Confirm New Password</label>
                    <input type="password" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                  </div>
                  
                  <div>
                    <button class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md shadow-sm flex items-center">
                      <KeyIcon class="h-4 w-4 mr-2" />
                      Update Password
                    </button>
                  </div>
                </div>
              </div>
              
              <div class="border-t border-gray-200 pt-6">
                <h3 class="text-sm font-medium text-gray-700 mb-3 flex items-center">
                  <LockClosedIcon class="h-4 w-4 mr-2" />
                  Two-Factor Authentication
                </h3>
                <p class="text-sm text-gray-500 mb-4">Add an extra layer of security to your account</p>
                
                <div class="flex items-start mb-4">
                  <div class="flex items-center h-5">
                    <input id="enable-2fa-profile" type="checkbox" class="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300 rounded">
                  </div>
                  <div class="ml-3 text-sm">
                    <label for="enable-2fa-profile" class="font-medium text-gray-700">Enable Two-Factor Authentication</label>
                    <p class="text-gray-500">We'll ask for a verification code in addition to your password when you sign in</p>
                  </div>
                </div>
                
                <button class="px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 flex items-center">
                  <LockClosedIcon class="h-4 w-4 mr-2" />
                  Set Up Two-Factor Authentication
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </DataLoader>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { 
  CameraIcon,
  EnvelopeIcon,
  ShieldCheckIcon,
  BuildingOfficeIcon,
  MapPinIcon,
  CalendarIcon,
  ClockIcon,
  UserIcon,
  IdentificationIcon,
  PhoneIcon,
  DocumentTextIcon,
  CheckCircleIcon,
  KeyIcon,
  LockClosedIcon
} from '@heroicons/vue/24/outline'

definePageMeta({
  middleware: 'auth',
  layout: 'dashboard'
})

const loading = ref(true)
const error = ref(null)
const saving = ref(false)

const tabs = [
  { id: 'information', name: 'Information', icon: UserIcon },
  { id: 'security', name: 'Security', icon: ShieldCheckIcon }
]

const activeTab = ref('information')

// Sample user data - in a real app, this would come from an API
const userData = ref({
  username: 'admin',
  fullName: 'Admin User',
  email: 'admin@example.com',
  phone: '+1 (555) 123-4567',
  role: 'Administrator',
  department: 'IT',
  location: 'New York, USA',
  memberSince: 'January 15, 2023',
  lastLogin: 'May 22, 2025',
  bio: 'System administrator with over 5 years of experience in managing enterprise applications and infrastructure.'
})

// Compute user initials from full name
const userInitials = computed(() => {
  if (!userData.value.fullName) return 'A'
  
  const nameParts = userData.value.fullName.split(' ')
  if (nameParts.length >= 2) {
    return `${nameParts[0][0]}${nameParts[1][0]}`
  }
  
  return userData.value.fullName[0]
})

const saveProfile = async () => {
  saving.value = true
  try {
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 2000))
    // Show success message or handle response
  } catch (err) {
    error.value = err.message || 'Failed to save profile'
  } finally {
    saving.value = false
  }
}

onMounted(async () => {
  try {
    // Simulate API call to load profile data
    await new Promise(resolve => setTimeout(resolve, 2000))
  } catch (err) {
    error.value = err.message || 'Failed to load profile'
  } finally {
    loading.value = false
  }
})
</script>

// app/dashboard/profile/page.tsx
"use client"

import type React from "react"

import { useState, useEffect } from "react"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import { Loader2, Camera, Key, Save } from "lucide-react"
import { useAuth } from "@/contexts/auth-context"
import { LoadingSpinner } from "@/components/loading-spinner"

// Mock profile data
const profileData = {
  id: 1,
  username: "admin",
  fullName: "Admin User",
  email: "admin@example.com",
  role: "Administrator",
  department: "IT",
  phone: "+1 (555) 123-4567",
  location: "New York, USA",
  bio: "System administrator with over 5 years of experience in managing enterprise applications and infrastructure.",
  joinDate: "2023-01-15T00:00:00",
  lastLogin: "2025-05-22T08:30:00",
  isActive: true,
  avatar: null,
}

export default function ProfilePage() {
  const { user } = useAuth()
  const [profile, setProfile] = useState(profileData)
  const [isLoading, setIsLoading] = useState(true)
  const [isSaving, setIsSaving] = useState(false)
  const [isChangingPassword, setIsChangingPassword] = useState(false)
  const [passwordData, setPasswordData] = useState({
    currentPassword: "",
    newPassword: "",
    confirmPassword: "",
  })

  // Simulate API call to fetch profile data
  useEffect(() => {
    const fetchProfile = async () => {
      setIsLoading(true)
      // Simulate API delay
      await new Promise((resolve) => setTimeout(resolve, 1000))
      setProfile({
        ...profileData,
        username: user?.username || profileData.username,
        email: user?.email || profileData.email,
      })
      setIsLoading(false)
    }

    fetchProfile()
  }, [user])

  const handleProfileUpdate = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsSaving(true)
    // Simulate API call to update profile
    await new Promise((resolve) => setTimeout(resolve, 1500))
    setIsSaving(false)
  }

  const handlePasswordChange = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsChangingPassword(true)
    // Simulate API call to change password
    await new Promise((resolve) => setTimeout(resolve, 1500))
    setPasswordData({
      currentPassword: "",
      newPassword: "",
      confirmPassword: "",
    })
    setIsChangingPassword(false)
  }

  const formatDate = (dateString: string) => {
    const date = new Date(dateString)
    return new Intl.DateTimeFormat("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    }).format(date)
  }

  if (isLoading) {
    return (
      <div className="flex h-[50vh] items-center justify-center">
        <LoadingSpinner size={8} />
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">My Profile</h1>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        <Card className="rounded-2xl shadow-sm md:col-span-1">
          <CardHeader className="flex flex-col items-center text-center">
            <div className="relative mb-4">
              <Avatar className="h-24 w-24">
                <AvatarImage src={profile.avatar || ""} alt={profile.username} />
                <AvatarFallback className="text-2xl">{profile.username.charAt(0).toUpperCase()}</AvatarFallback>
              </Avatar>
              <Button
                size="icon"
                className="absolute bottom-0 right-0 h-8 w-8 rounded-full bg-primary text-white shadow-md"
              >
                <Camera className="h-4 w-4" />
                <span className="sr-only">Change avatar</span>
              </Button>
            </div>
            <CardTitle>{profile.fullName}</CardTitle>
            <CardDescription>{profile.email}</CardDescription>
            <Badge variant="outline" className="mt-2 rounded-full bg-blue-50 text-blue-700 border-blue-200 px-3 py-1">
              {profile.role}
            </Badge>
          </CardHeader>
          <CardContent className="space-y-4 text-center">
            <div>
              <p className="text-sm text-gray-500">Department</p>
              <p className="font-medium">{profile.department}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Location</p>
              <p className="font-medium">{profile.location}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Member Since</p>
              <p className="font-medium">{formatDate(profile.joinDate)}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Last Login</p>
              <p className="font-medium">{formatDate(profile.lastLogin)}</p>
            </div>
          </CardContent>
        </Card>

        <Card className="rounded-2xl shadow-sm md:col-span-2">
          <Tabs defaultValue="info" className="w-full">
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle>Profile Details</CardTitle>
                <TabsList className="grid w-[240px] grid-cols-2 rounded-xl">
                  <TabsTrigger value="info">Information</TabsTrigger>
                  <TabsTrigger value="security">Security</TabsTrigger>
                </TabsList>
              </div>
              <CardDescription>Manage your personal information and account security</CardDescription>
            </CardHeader>

            <TabsContent value="info" className="space-y-4 px-6">
              <form onSubmit={handleProfileUpdate}>
                <div className="grid gap-4 py-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="username">Username</Label>
                    <Input
                      id="username"
                      value={profile.username}
                      onChange={(e) => setProfile({ ...profile, username: e.target.value })}
                      className="rounded-xl"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="fullName">Full Name</Label>
                    <Input
                      id="fullName"
                      value={profile.fullName}
                      onChange={(e) => setProfile({ ...profile, fullName: e.target.value })}
                      className="rounded-xl"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="email">Email</Label>
                    <Input
                      id="email"
                      type="email"
                      value={profile.email}
                      onChange={(e) => setProfile({ ...profile, email: e.target.value })}
                      className="rounded-xl"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="phone">Phone</Label>
                    <Input
                      id="phone"
                      value={profile.phone}
                      onChange={(e) => setProfile({ ...profile, phone: e.target.value })}
                      className="rounded-xl"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="department">Department</Label>
                    <Input
                      id="department"
                      value={profile.department}
                      onChange={(e) => setProfile({ ...profile, department: e.target.value })}
                      className="rounded-xl"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="location">Location</Label>
                    <Input
                      id="location"
                      value={profile.location}
                      onChange={(e) => setProfile({ ...profile, location: e.target.value })}
                      className="rounded-xl"
                    />
                  </div>
                  <div className="space-y-2 md:col-span-2">
                    <Label htmlFor="bio">Bio</Label>
                    <textarea
                      id="bio"
                      rows={4}
                      value={profile.bio}
                      onChange={(e) => setProfile({ ...profile, bio: e.target.value })}
                      className="w-full rounded-xl border border-gray-300 p-2 text-sm"
                    />
                  </div>
                </div>

                <CardFooter className="flex justify-end border-t px-0 pt-4">
                  <Button type="submit" className="rounded-xl" disabled={isSaving}>
                    {isSaving ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        Saving...
                      </>
                    ) : (
                      <>
                        <Save className="mr-2 h-4 w-4" />
                        Save Changes
                      </>
                    )}
                  </Button>
                </CardFooter>
              </form>
            </TabsContent>

            <TabsContent value="security" className="space-y-4 px-6">
              <div className="space-y-4">
                <h3 className="text-lg font-medium">Change Password</h3>
                <form onSubmit={handlePasswordChange}>
                  <div className="grid gap-4 py-4">
                    <div className="space-y-2">
                      <Label htmlFor="currentPassword">Current Password</Label>
                      <Input
                        id="currentPassword"
                        type="password"
                        value={passwordData.currentPassword}
                        onChange={(e) => setPasswordData({ ...passwordData, currentPassword: e.target.value })}
                        className="rounded-xl"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="newPassword">New Password</Label>
                      <Input
                        id="newPassword"
                        type="password"
                        value={passwordData.newPassword}
                        onChange={(e) => setPasswordData({ ...passwordData, newPassword: e.target.value })}
                        className="rounded-xl"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="confirmPassword">Confirm New Password</Label>
                      <Input
                        id="confirmPassword"
                        type="password"
                        value={passwordData.confirmPassword}
                        onChange={(e) => setPasswordData({ ...passwordData, confirmPassword: e.target.value })}
                        className="rounded-xl"
                      />
                    </div>
                  </div>

                  <CardFooter className="flex justify-end border-t px-0 pt-4">
                    <Button type="submit" className="rounded-xl" disabled={isChangingPassword}>
                      {isChangingPassword ? (
                        <>
                          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                          Changing...
                        </>
                      ) : (
                        <>
                          <Key className="mr-2 h-4 w-4" />
                          Change Password
                        </>
                      )}
                    </Button>
                  </CardFooter>
                </form>
              </div>

              <Separator />

              <div className="space-y-4">
                <h3 className="text-lg font-medium">Two-Factor Authentication</h3>
                <p className="text-sm text-gray-500">
                  Add an extra layer of security to your account by enabling two-factor authentication.
                </p>
                <Button variant="outline" className="rounded-xl">
                  Enable Two-Factor Authentication
                </Button>
              </div>

              <Separator />

              <div className="space-y-4">
                <h3 className="text-lg font-medium">Active Sessions</h3>
                <div className="rounded-xl border p-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="font-medium">Current Session</p>
                      <p className="text-sm text-gray-500">
                        Chrome on Windows • IP: 192.168.1.1 • Last active: Just now
                      </p>
                    </div>
                    <Badge variant="outline" className="bg-green-100 text-green-800 border-green-200">
                      Active
                    </Badge>
                  </div>
                </div>
              </div>
            </TabsContent>
          </Tabs>
        </Card>
      </div>
    </div>
  )
}
