// pages/dashboard/settings.vue
<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <h1 class="text-2xl font-bold">Settings</h1>
      <button 
        @click="saveSettings" 
        :disabled="saving"
        class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md flex items-center shadow-md disabled:opacity-50"
      >
        <CheckCircleIcon v-if="!saving" class="h-5 w-5 mr-1" />
        <div v-else class="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-1"></div>
        {{ saving ? 'Saving...' : 'Save Changes' }}
      </button>
    </div>
    
    <!-- Settings Tabs -->
    <div class="bg-white rounded-lg shadow-md border border-gray-200 overflow-hidden mb-6">
      <div class="flex border-b border-gray-200">
        <button 
          v-for="tab in tabs" 
          :key="tab.id" 
          @click="activeTab = tab.id" 
          class="px-6 py-3 text-sm font-medium focus:outline-none flex items-center"
          :class="activeTab === tab.id ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500 hover:text-gray-700'"
        >
          <component :is="tab.icon" class="h-5 w-5 mr-2" />
          {{ tab.name }}
        </button>
      </div>
    </div>
    
    <DataLoader :loading="loading" :error="error">
      <!-- General Settings -->
      <div v-if="activeTab === 'general'" class="bg-white rounded-lg shadow-md border border-gray-200 overflow-hidden">
        <div class="p-4 border-b border-gray-200">
          <div class="flex items-center">
            <Cog6ToothIcon class="h-6 w-6 text-blue-600 mr-2" />
            <div>
              <h2 class="text-lg font-semibold">General Settings</h2>
              <p class="text-sm text-gray-500">Manage your general dashboard preferences</p>
            </div>
          </div>
        </div>
        
        <div class="p-6 space-y-6">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1 flex items-center">
              <GlobeAltIcon class="h-4 w-4 mr-2" />
              Language
            </label>
            <p class="text-xs text-gray-500 mb-2">Select your preferred language</p>
            <div class="relative">
              <select class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                <option>English</option>
                <option>Spanish</option>
                <option>French</option>
                <option>German</option>
                <option>Japanese</option>
              </select>
              <div class="absolute inset-y-0 right-0 flex items-center px-2 pointer-events-none">
                <ChevronDownIcon class="h-4 w-4 text-gray-400" />
              </div>
            </div>
          </div>
          
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1 flex items-center">
              <ClockIcon class="h-4 w-4 mr-2" />
              Time Zone
            </label>
            <p class="text-xs text-gray-500 mb-2">Set your local time zone</p>
            <div class="relative">
              <select class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                <option>UTC</option>
                <option>UTC-05:00 (Eastern Time)</option>
                <option>UTC-08:00 (Pacific Time)</option>
                <option>UTC+01:00 (Central European Time)</option>
                <option>UTC+09:00 (Japan Standard Time)</option>
              </select>
              <div class="absolute inset-y-0 right-0 flex items-center px-2 pointer-events-none">
                <ChevronDownIcon class="h-4 w-4 text-gray-400" />
              </div>
            </div>
          </div>
          
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1 flex items-center">
              <CalendarIcon class="h-4 w-4 mr-2" />
              Date Format
            </label>
            <p class="text-xs text-gray-500 mb-2">Choose how dates are displayed</p>
            <div class="relative">
              <select class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                <option>MM/DD/YYYY</option>
                <option>DD/MM/YYYY</option>
                <option>YYYY-MM-DD</option>
                <option>YYYY/MM/DD</option>
                <option>DD-MMM-YYYY</option>
              </select>
              <div class="absolute inset-y-0 right-0 flex items-center px-2 pointer-events-none">
                <ChevronDownIcon class="h-4 w-4 text-gray-400" />
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Notifications Settings -->
      <div v-if="activeTab === 'notifications'" class="bg-white rounded-lg shadow-md border border-gray-200 overflow-hidden">
        <div class="p-4 border-b border-gray-200">
          <div class="flex items-center">
            <BellIcon class="h-6 w-6 text-blue-600 mr-2" />
            <div>
              <h2 class="text-lg font-semibold">Notification Settings</h2>
              <p class="text-sm text-gray-500">Manage how you receive notifications</p>
            </div>
          </div>
        </div>
        
        <div class="p-6 space-y-6">
          <div>
            <h3 class="text-sm font-medium text-gray-700 mb-3 flex items-center">
              <EnvelopeIcon class="h-4 w-4 mr-2" />
              Email Notifications
            </h3>
            
            <div class="space-y-4">
              <div class="flex items-start">
                <div class="flex items-center h-5">
                  <input id="email-notifications" type="checkbox" class="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300 rounded">
                </div>
                <div class="ml-3 text-sm">
                  <label for="email-notifications" class="font-medium text-gray-700">Email Notifications</label>
                  <p class="text-gray-500">Receive email notifications for important updates</p>
                </div>
              </div>
              
              <div class="flex items-start">
                <div class="flex items-center h-5">
                  <input id="security-alerts" type="checkbox" class="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300 rounded">
                </div>
                <div class="ml-3 text-sm">
                  <label for="security-alerts" class="font-medium text-gray-700">Security Alerts</label>
                  <p class="text-gray-500">Receive email notifications for security-related events</p>
                </div>
              </div>
            </div>
          </div>
          
          <div class="border-t border-gray-200 pt-6">
            <h3 class="text-sm font-medium text-gray-700 mb-3 flex items-center">
              <DevicePhoneMobileIcon class="h-4 w-4 mr-2" />
              In-App Notifications
            </h3>
            
            <div class="space-y-4">
              <div class="flex items-start">
                <div class="flex items-center h-5">
                  <input id="in-app-notifications" type="checkbox" class="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300 rounded">
                </div>
                <div class="ml-3 text-sm">
                  <label for="in-app-notifications" class="font-medium text-gray-700">In-App Notifications</label>
                  <p class="text-gray-500">Receive notifications within the application</p>
                </div>
              </div>
              
              <div class="flex items-start">
                <div class="flex items-center h-5">
                  <input id="notification-sound" type="checkbox" class="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300 rounded">
                </div>
                <div class="ml-3 text-sm">
                  <label for="notification-sound" class="font-medium text-gray-700">Notification Sound</label>
                  <p class="text-gray-500">Play a sound when a notification is received</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Security Settings -->
      <div v-if="activeTab === 'security'" class="bg-white rounded-lg shadow-md border border-gray-200 overflow-hidden">
        <div class="p-4 border-b border-gray-200">
          <div class="flex items-center">
            <ShieldCheckIcon class="h-6 w-6 text-blue-600 mr-2" />
            <div>
              <h2 class="text-lg font-semibold">Security Settings</h2>
              <p class="text-sm text-gray-500">Manage your account security</p>
            </div>
          </div>
        </div>
        
        <div class="p-6 space-y-6">
          <div>
            <h3 class="text-sm font-medium text-gray-700 mb-3 flex items-center">
              <KeyIcon class="h-4 w-4 mr-2" />
              Change Password
            </h3>
            
            <div class="space-y-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Current Password</label>
                <input type="password" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
              </div>
              
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">New Password</label>
                <input type="password" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
              </div>
              
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Confirm New Password</label>
                <input type="password" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
              </div>
              
              <div>
                <button class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md shadow-sm flex items-center">
                  <KeyIcon class="h-4 w-4 mr-2" />
                  Update Password
                </button>
              </div>
            </div>
          </div>
          
          <div class="border-t border-gray-200 pt-6">
            <h3 class="text-sm font-medium text-gray-700 mb-3 flex items-center">
              <LockClosedIcon class="h-4 w-4 mr-2" />
              Two-Factor Authentication
            </h3>
            <p class="text-sm text-gray-500 mb-4">Add an extra layer of security to your account</p>
            
            <div class="flex items-start mb-4">
              <div class="flex items-center h-5">
                <input id="enable-2fa" type="checkbox" class="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300 rounded">
              </div>
              <div class="ml-3 text-sm">
                <label for="enable-2fa" class="font-medium text-gray-700">Enable Two-Factor Authentication</label>
                <p class="text-gray-500">We'll ask for a verification code in addition to your password when you sign in</p>
              </div>
            </div>
            
            <button class="px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 flex items-center">
              <LockClosedIcon class="h-4 w-4 mr-2" />
              Set Up Two-Factor Authentication
            </button>
          </div>
        </div>
      </div>
    </DataLoader>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { definePageMeta } from '#imports'
import { 
  CheckCircleIcon,
  Cog6ToothIcon,
  BellIcon,
  ShieldCheckIcon,
  GlobeAltIcon,
  ClockIcon,
  CalendarIcon,
  ChevronDownIcon,
  EnvelopeIcon,
  DevicePhoneMobileIcon,
  KeyIcon,
  LockClosedIcon
} from '@heroicons/vue/24/outline'

definePageMeta({
  middleware: 'auth',
  layout: 'dashboard'
})

const loading = ref(true)
const error = ref(null)
const saving = ref(false)

const tabs = [
  { id: 'general', name: 'General', icon: Cog6ToothIcon },
  { id: 'notifications', name: 'Notifications', icon: BellIcon },
  { id: 'security', name: 'Security', icon: ShieldCheckIcon }
]

const activeTab = ref('general')

const saveSettings = async () => {
  saving.value = true
  try {
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 2000))
    // Show success message or handle response
  } catch (err) {
    error.value = err.message || 'Failed to save settings'
  } finally {
    saving.value = false
  }
}

onMounted(async () => {
  try {
    // Simulate API call to load settings
    await new Promise(resolve => setTimeout(resolve, 1000))
  } catch (err) {
    error.value = err.message || 'Failed to load settings'
  } finally {
    loading.value = false
  }
})
</script>

// app/dashboard/settings/page.tsx
"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Input } from "@/components/ui/input"
import { Loader2, Save } from "lucide-react"
import { useTheme } from "next-themes"
import { Separator } from "@/components/ui/separator"
import { LoadingSpinner } from "@/components/loading-spinner"

// Mock settings data
const initialSettings = {
  notifications: {
    email: true,
    push: false,
    sms: false,
    inApp: true,
  },
  security: {
    twoFactor: false,
    sessionTimeout: 30,
    passwordExpiry: 90,
  },
  appearance: {
    compactMode: false,
    animationsEnabled: true,
  },
}

export default function SettingsPage() {
  const [settings, setSettings] = useState(initialSettings)
  const [isLoading, setIsLoading] = useState(true)
  const [isSaving, setIsSaving] = useState(false)
  const { theme, setTheme } = useTheme()

  // Simulate API call to fetch settings
  useEffect(() => {
    const fetchSettings = async () => {
      setIsLoading(true)
      // Simulate API delay
      await new Promise((resolve) => setTimeout(resolve, 1000))
      setSettings(initialSettings)
      setIsLoading(false)
    }

    fetchSettings()
  }, [])

  const handleSaveSettings = async () => {
    setIsSaving(true)
    // Simulate API call to save settings
    await new Promise((resolve) => setTimeout(resolve, 1500))
    setIsSaving(false)
  }

  if (isLoading) {
    return (
      <div className="flex h-[50vh] items-center justify-center">
        <LoadingSpinner size={8} />
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Settings</h1>
        <Button className="rounded-xl" onClick={handleSaveSettings} disabled={isSaving}>
          {isSaving ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Saving...
            </>
          ) : (
            <>
              <Save className="mr-2 h-4 w-4" />
              Save Changes
            </>
          )}
        </Button>
      </div>

      <Tabs defaultValue="general" className="w-full">
        <TabsList className="grid w-full grid-cols-4 rounded-xl">
          <TabsTrigger value="general">General</TabsTrigger>
          <TabsTrigger value="notifications">Notifications</TabsTrigger>
          <TabsTrigger value="security">Security</TabsTrigger>
          <TabsTrigger value="appearance">Appearance</TabsTrigger>
        </TabsList>

        <TabsContent value="general" className="mt-4">
          <Card className="rounded-2xl shadow-sm">
            <CardHeader>
              <CardTitle>General Settings</CardTitle>
              <CardDescription>Manage your general dashboard preferences</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">Language</h3>
                    <p className="text-sm text-gray-500">Select your preferred language</p>
                  </div>
                  <div className="w-[180px]">
                    <select className="w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm">
                      <option value="en">English</option>
                      <option value="fr">French</option>
                      <option value="de">German</option>
                      <option value="es">Spanish</option>
                      <option value="th">Thai</option>
                    </select>
                  </div>
                </div>

                <Separator />

                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">Time Zone</h3>
                    <p className="text-sm text-gray-500">Set your local time zone</p>
                  </div>
                  <div className="w-[180px]">
                    <select className="w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm">
                      <option value="utc">UTC</option>
                      <option value="est">Eastern Time (ET)</option>
                      <option value="cst">Central Time (CT)</option>
                      <option value="pst">Pacific Time (PT)</option>
                      <option value="bkk">Bangkok (ICT)</option>
                    </select>
                  </div>
                </div>

                <Separator />

                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">Date Format</h3>
                    <p className="text-sm text-gray-500">Choose how dates are displayed</p>
                  </div>
                  <div className="w-[180px]">
                    <select className="w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm">
                      <option value="mdy">MM/DD/YYYY</option>
                      <option value="dmy">DD/MM/YYYY</option>
                      <option value="ymd">YYYY/MM/DD</option>
                    </select>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="notifications" className="mt-4">
          <Card className="rounded-2xl shadow-sm">
            <CardHeader>
              <CardTitle>Notification Settings</CardTitle>
              <CardDescription>Manage how you receive notifications</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">Email Notifications</h3>
                    <p className="text-sm text-gray-500">Receive notifications via email</p>
                  </div>
                  <Switch
                    checked={settings.notifications.email}
                    onCheckedChange={(checked) =>
                      setSettings({
                        ...settings,
                        notifications: { ...settings.notifications, email: checked },
                      })
                    }
                  />
                </div>

                <Separator />

                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">Push Notifications</h3>
                    <p className="text-sm text-gray-500">Receive push notifications in browser</p>
                  </div>
                  <Switch
                    checked={settings.notifications.push}
                    onCheckedChange={(checked) =>
                      setSettings({
                        ...settings,
                        notifications: { ...settings.notifications, push: checked },
                      })
                    }
                  />
                </div>

                <Separator />

                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">SMS Notifications</h3>
                    <p className="text-sm text-gray-500">Receive notifications via SMS</p>
                  </div>
                  <Switch
                    checked={settings.notifications.sms}
                    onCheckedChange={(checked) =>
                      setSettings({
                        ...settings,
                        notifications: { ...settings.notifications, sms: checked },
                      })
                    }
                  />
                </div>

                <Separator />

                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">In-App Notifications</h3>
                    <p className="text-sm text-gray-500">Show notifications within the dashboard</p>
                  </div>
                  <Switch
                    checked={settings.notifications.inApp}
                    onCheckedChange={(checked) =>
                      setSettings({
                        ...settings,
                        notifications: { ...settings.notifications, inApp: checked },
                      })
                    }
                  />
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="security" className="mt-4">
          <Card className="rounded-2xl shadow-sm">
            <CardHeader>
              <CardTitle>Security Settings</CardTitle>
              <CardDescription>Manage your account security preferences</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">Two-Factor Authentication</h3>
                    <p className="text-sm text-gray-500">Add an extra layer of security to your account</p>
                  </div>
                  <Switch
                    checked={settings.security.twoFactor}
                    onCheckedChange={(checked) =>
                      setSettings({
                        ...settings,
                        security: { ...settings.security, twoFactor: checked },
                      })
                    }
                  />
                </div>

                <Separator />

                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">Session Timeout (minutes)</h3>
                    <p className="text-sm text-gray-500">Automatically log out after inactivity</p>
                  </div>
                  <div className="w-[100px]">
                    <Input
                      type="number"
                      min="5"
                      max="120"
                      className="rounded-xl"
                      value={settings.security.sessionTimeout}
                      onChange={(e) =>
                        setSettings({
                          ...settings,
                          security: { ...settings.security, sessionTimeout: Number.parseInt(e.target.value) || 30 },
                        })
                      }
                    />
                  </div>
                </div>

                <Separator />

                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">Password Expiry (days)</h3>
                    <p className="text-sm text-gray-500">Force password change after specified days</p>
                  </div>
                  <div className="w-[100px]">
                    <Input
                      type="number"
                      min="0"
                      max="365"
                      className="rounded-xl"
                      value={settings.security.passwordExpiry}
                      onChange={(e) =>
                        setSettings({
                          ...settings,
                          security: { ...settings.security, passwordExpiry: Number.parseInt(e.target.value) || 90 },
                        })
                      }
                    />
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="appearance" className="mt-4">
          <Card className="rounded-2xl shadow-sm">
            <CardHeader>
              <CardTitle>Appearance Settings</CardTitle>
              <CardDescription>Customize how the dashboard looks</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">Theme</h3>
                    <p className="text-sm text-gray-500">Choose light or dark theme</p>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Button
                      variant={theme === "light" ? "default" : "outline"}
                      size="sm"
                      className="rounded-xl"
                      onClick={() => setTheme("light")}
                    >
                      Light
                    </Button>
                    <Button
                      variant={theme === "dark" ? "default" : "outline"}
                      size="sm"
                      className="rounded-xl"
                      onClick={() => setTheme("dark")}
                    >
                      Dark
                    </Button>
                    <Button
                      variant={theme === "system" ? "default" : "outline"}
                      size="sm"
                      className="rounded-xl"
                      onClick={() => setTheme("system")}
                    >
                      System
                    </Button>
                  </div>
                </div>

                <Separator />

                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">Compact Mode</h3>
                    <p className="text-sm text-gray-500">Reduce spacing in the interface</p>
                  </div>
                  <Switch
                    checked={settings.appearance.compactMode}
                    onCheckedChange={(checked) =>
                      setSettings({
                        ...settings,
                        appearance: { ...settings.appearance, compactMode: checked },
                      })
                    }
                  />
                </div>

                <Separator />

                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-medium">Animations</h3>
                    <p className="text-sm text-gray-500">Enable interface animations</p>
                  </div>
                  <Switch
                    checked={settings.appearance.animationsEnabled}
                    onCheckedChange={(checked) =>
                      setSettings({
                        ...settings,
                        appearance: { ...settings.appearance, animationsEnabled: checked },
                      })
                    }
                  />
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}
